import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { CreatePostWizard, Feed } from "~/components";

import { api } from "~/utils/api";

export default function Home() {
  const { isLoaded, isSignedIn } = useUser();

  api.posts.getAll.useQuery();

  if (!isLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full border-x border-slate-400 md:max-w-2xl">
        <div className="flex border-b border-slate-400 p-4">
          {!isSignedIn ? (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          ) : (
            <>
              <CreatePostWizard />
            </>
          )}
        </div>
        <Feed />
      </div>
    </>
  );
}
